title: 2ª SEMATIF
description: > # this means to ignore newlines until "baseurl:"
  Site da semana da matemática do IFSP campus Itapetininga
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://matematicaifspitp.github.io" # the base hostname & protocol for your site
# Build settings
markdown: kramdown

facebook:
  app_id: 

logo: "../css/2016_style/img/sematif4.png"

social: 
  name: Facebook Page
  link: "https://pt-br.facebook.com/IFSPItapetininga/"

google_site_verification: google0496d01d73be33b9.html

include: ['_2016_pages', '_2017_pages']

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://pt-br.facebook.com/IFSPItapetininga/
  - title: twitter
    url: https://twitter.com/ifspitape

# Build settings
markdown: kramdown
permalink: pretty
